CREATE TABLE USERS(
	ID varchar(10) PRIMARY KEY,
    NAME varchar(20) NOT NULL,
    PASSWORD varchar(10) NOT NULL
);

SELECT * FROM USERS;
DELETE FROM USERS WHERE ID='dohyun';

ALTER TABLE USERS ADD LEVEL tinyint NOT NULL;
ALTER TABLE USERS ADD LOGIN int NOT NULL;
ALTER TABLE USERS ADD RECOMMEND INT NOT NULL;
ALTER TABLE USERS ADD EMAIL varchar(50) NOT NULL;